[project]
name = "supergene"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Maxwell Ludden", email = "dev@maxludden.com" }
]
dependencies = [
    "rich>=13.9.1",
    "loguru>=0.7.2",
    "rich-gradient>=0.1.7",
    "sh>=2.0.7",
    "python-dotenv[cli]>=1.0.1",
    "pydantic>=2.9.2",
    "pymongo>=4.10.1",
    "bunnet>=1.3.0",
    "pip>=24.2",
    "fastapi>=0.115.0",
    "uvicorn>=0.31.0",
    "jinja2>=3.1.4",
]
readme = "README.md"
requires-python = ">= 3.12"
license = { text = "MIT" }

[project.scripts]
"supergene" = "supergene:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/supergene"]

[tool.ruff]
ignore = ["F401"]
